apiVersion: {{ template "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "common.names.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.image "global" .Values.global) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.existingSecret .Values.db2.password }}
          envFrom:
          - secretRef:
              name: {{- if .Values.db2.password }} {{ include "common.names.fullname" . }} {{ else }} {{ .Values.existingSecret }} {{ end }}
              optional: false
          {{- end }}
          env:
          - name: IBM_DB2_EXPORTER_DB
            value: {{ .Values.db2.database | quote }}
          - name: IBM_DB2_EXPORTER_DSN
            value: "DATABASE={{ .Values.db2.database }};HOSTNAME={{ .Values.db2.hostname }};PORT={{ .Values.db2.port }};UID={{ .Values.db2.userId }};PWD=$(DB2PASSWORD);"
          {{- if .Values.db2.instanceSecret }}
          - name: DB2PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.db2.instanceSecret }}
                key: password
          {{- end }}
          args:
            {{- toYaml .Values.args | nindent 10 }}
          ports:
          - name: metrics
            containerPort: 9953
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: metrics
          readinessProbe:
            httpGet:
              path: /
              port: metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
